name: fot-valuing-actions
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.5.3
  - ipywidgets=7.6.3
  - numpy=1.20.2
  - pandas=1.2.4
  - pip=21.1
  - pytables=3.6.1
  - python=3.8.8
  - scikit-learn=0.24.1
  - scikit-plot=0.3.7
  - scipy=1.6.2
  - shap=0.37.0
  - tqdm=4.60.0
  - xgboost=1.3.3
  - pip:
    - matplotsoccer==0.0.8
    - socceraction==0.2.0
